name: "Jin Heo"
title: "Jin Heo"
description: "Personal Website of Jin Heo"

url: 'https://jheo4.github.io'
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
paginate: 10
paginate_path: /page-:num

disqus-id: 'jheo4'

source:
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

